name: FabLab Community
favicon: null
layout_spectrum: 0
typography_spectrum: 0.31434
title: FabLab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#000000'
    - '#666666'
    - '#767676'
    - '#555555'
  brandStrength: 0.7794030143413693
  lightness: 0.9237294183112681
  saturation: 0.37687585270032287
  rhythmicContrast: 0.6490774885751307
purpose: []
