name: FabLab Community
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38623
title: FabLab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#003366'
    - '#000000'
    - '#000055'
    - '#555555'
  brandStrength: 0
  lightness: 0.9237294183112681
  saturation: 0.37687585270032287
  rhythmicContrast: 0.75
purpose: []
