name: FabLab Community
favicon: null
layout_spectrum: 0.47561
typography_spectrum: 0.38623
title: FabLab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#003366'
    - '#000000'
    - '#000055'
    - '#555555'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
