name: FabLab Community
favicon: null
layout_spectrum: 0.74173
typography_spectrum: 0.15371
title: FabLab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a86b'
    - '#808080'
    - '#003464'
    - '#00555e'
    - '#04736c'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
